server:
  port: 8081
spring:
  application:
    name: AudioShopApiService
  datasource:
    url: jdbc:postgresql://localhost:5432/audio_shop
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: false
  messages:
    encoding: UTF-8
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


app:
  images:
    path: images
    not-found: not_image.png
    base-url: http://localhost
